### ISSUE TITLE
Data type 'System.Uri' with configured HasConversion(...) not supported in bulk operations

### ISSUE THREAD

**Issue by blackwork** [schwarzr/EFCoreBulk#7]
When data type `System.Uri` is used in C# model and `.HasConversion(v => v.ToString(), v => new Uri(v))´ is used entity configuration, add bulk operation is not supported / not working.

An exception is thrown:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The given value of type Uri from the data source cannot be converted to type nvarchar of the specified target column.
  Source=System.Data
  StackTrace:
   at System.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)
   at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
   at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Bulk.Internal.SqlServerBulkProcessor`1.<ProcessAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkCoreSqlServerBulkDbContextExtensions.<BulkInsertAsync>d__0`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   ...

  This exception was originally thrown at this call stack:
    System.Convert.ChangeType(object, System.Type, System.IFormatProvider)
    System.Data.SqlClient.SqlParameter.CoerceValue(object, System.Data.SqlClient.MetaType, out bool, out bool, bool)

Inner Exception 1:
InvalidCastException: Failed to convert parameter value from a Uri to a String.

Inner Exception 2:
InvalidCastException: Object must implement IConvertible.
```

Regards
  Michael

**Comment by schwarzr** [comment]
Fixed in version 3.1.2, 5.0.0 and 6.0.0
